# Site settings
title: Сергей Панфилов
email: flakessp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Javаscript веб разработчик и путешественник
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: krasivieglaza
github_username:  flakessp

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown
